* Mouse Follows Focus
  :PROPERTIES:
  :ID:       f70ba9fb-55df-4040-a4f0-54ffeaeced84
  :END:

  Many traditional window managers offer a focus-follows-mouse mode,
  where moving the pointer over a window gives it input focus, without
  the need to click.

  With Emacs' keyboard-centric interaction, windows are typically
  selected with the keyboard.  However, using the keyboard breaks the
  spatial relationship between focused window and mouse pointer, which
  makes it harder to find the pointer location when you need to use
  it.

  The appropriate focusing model for this is the inverse of
  focus-follows-mouse -- instead of using4 the mouse to select the
  window to receive keyboard input, the keyboard should be used to
  select the window to receive mouse input.

  =EXWM-MFF-MODE= is a global minor mode which does exactly that.
  When the selected window in Emacs changes, the mouse pointer is
  moved to the center of it (unless the pointer is already within the
  window’s bounds).  It works for both regular Emacs windows
  and ones managed by EXWM.

  If you don't like the automatic behavior, you can bind
  =EXWM-MFF-WARP-TO-SELECTED-WINDOW= which allows you to summon the
  pointer with a hotkey.
